import PageHeader from "../../components/ui/PageHeader"
import GlassCard from "../../components/ui/GlassCard"
import PrimaryButton from "../../components/ui/PrimaryButton"

function Reports() {
  const reports = [
    {
      name: "Cyber Crime Analysis Report",
      date: "04 Jul 2026",
      officer: "Officer Raj",
      status: "Generated",
    },
    {
      name: "Bengaluru Crime Summary",
      date: "03 Jul 2026",
      officer: "Officer Kumar",
      status: "Downloaded",
    },
    {
      name: "Repeat Offender Report",
      date: "02 Jul 2026",
      officer: "Admin",
      status: "Generated",
    },
  ]

  return (
    <div className="space-y-6">
      <PageHeader
        label="PDF Report Center"
        title="Reports"
        description="Generate, download and manage AI generated crime reports."
      />

      <GlassCard>
        <div className="flex flex-wrap gap-4">
          <PrimaryButton>Generate New Report</PrimaryButton>

          <PrimaryButton variant="outline">
            Export All PDFs
          </PrimaryButton>
        </div>
      </GlassCard>

      <GlassCard>
        <h3 className="text-xl font-bold text-white">
          Generated Reports
        </h3>

        <div className="mt-6 overflow-hidden rounded-2xl border border-white/10">
          <table className="w-full text-left">
            <thead className="bg-cyan-400/10 text-cyan-200">
              <tr>
                <th className="px-5 py-4">Report</th>
                <th className="px-5 py-4">Date</th>
                <th className="px-5 py-4">Generated By</th>
                <th className="px-5 py-4">Status</th>
                <th className="px-5 py-4">Action</th>
              </tr>
            </thead>

            <tbody className="divide-y divide-white/10">
              {reports.map((item) => (
                <tr
                  key={item.name}
                  className="bg-slate-950/60 text-slate-300"
                >
                  <td className="px-5 py-5 font-semibold text-white">
                    {item.name}
                  </td>

                  <td className="px-5 py-5">{item.date}</td>

                  <td className="px-5 py-5">{item.officer}</td>

                  <td className="px-5 py-5">
                    <span className="rounded-full bg-emerald-500/10 px-3 py-1 text-sm text-emerald-300">
                      {item.status}
                    </span>
                  </td>

                  <td className="px-5 py-5">
                    <PrimaryButton variant="ghost">
                      Download
                    </PrimaryButton>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </GlassCard>
    </div>
  )
}

export default Reports